image: microsoft/dotnet

before_script:
    - git submodule update --init --recursive

stages:
  - deploy

pages:
    stage: deploy
    only:
      - master
    script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet tool install -g Wyam.Tool
    - wyam -v --output output
    - rm -rf public
    - mv output public
    artifacts:
      paths:
        - public
